# Generated by Django 3.0.3 on 2022-11-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votingandresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('results', models.BooleanField(default=False)),
            ],
        ),
    ]
