# Generated by Django 3.0.3 on 2022-11-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_votingandresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultrelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votingrelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.BooleanField(default=False)),
                ('time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Votingandresults',
        ),
    ]
